### ISSUE TITLE
ElDorado- Final Capstone Kanban

### ISSUE THREAD

**Issue by michael-duke** [michael-duke/ElDorado-Backend#12]
## Final Capstone Kanban Review
- <img width="346" alt="logo2" src="https://user-images.githubusercontent.com/84629565/210569472-622286af-bae6-4692-868e-093de0f944a3.png">

In this issue we have: 
- Recognized we area group of 4 Micronauts: @aamirkhan2478 , @AbelG101 , @milen-ale , and @michael-duke 
- Assigned tasks to members and group tasks
- Here is a link to the [ElDorado-Frontend](https://github.com/michael-duke/ElDorado-Frontend/projects/1)
 - <img width="457" alt="image" src="https://user-images.githubusercontent.com/84629565/210576403-898f178a-227b-4006-a015-d8bce5da25ea.png">
 - <img width="460" alt="image" src="https://user-images.githubusercontent.com/84629565/210576590-0ec034c7-7f7c-40d7-9426-c6ed4a073cc4.png">

- Here is a link to the [ElDorado-Backend](https://github.com/michael-duke/ElDorado-Backend/projects/1)
   - <img width="436" alt="image" src="https://user-images.githubusercontent.com/84629565/210576949-48aefaf9-bd4f-4cde-ae3d-2b62c2162aff.png">
   - <img width="425" alt="image" src="https://user-images.githubusercontent.com/84629565/210577192-d58d11e1-fa0b-4d62-aee0-380fc95aff7f.png">

**Comment by Meltrust** [comment]
Hi @michael-duke

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have assignees✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️


- [ ] There is a task without points:

![image](https://user-images.githubusercontent.com/57421823/210572774-407ba389-f754-4cd8-bc7e-fa3fc9619bce.png)

Kindly, add points to that task.

note:  Remember that the points assignments for any member should never be more than 4 points above or below another teammate.

- [ ] Kindly, add a screenshot of the kanban board, as stated in the requirements.





## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by michael-duke** [comment]
@Meltrust , thank you for your feedback, we have made the changes suggested 😄

**Comment by Meltrust** [comment]
Hi @michael-duke,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks now have points✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by michael-duke** [comment]
Thank you @Meltrust , and happy coding 😄 🚀
